# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Photo Name'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
