# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20170712_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Photo'),
        ),
    ]
