# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170716_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
