# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='counter'),
        ),
    ]
