# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20170719_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='photo',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
